#@String 
from ij import IJ


IJ.run("Define Multi-View Dataset", (
        "define_dataset=[Automatic Loader (Bioformats based)]\n "
        "project_filename=dataset.xml\n "
        "path=[D:/James/2026-01-23/N001/10 mW/subsampled]\n "
        "exclude=10\n "
        "pattern_0=Tiles\n "
        "move_tiles_to_grid_(per_angle)?=[Move Tile to Grid (Macro-scriptable)]\n "
        "grid_type=[Snake: Down & Right      ]\n "
        "tiles_x=2\n "
        "tiles_y=2\n "
        "tiles_z=1\n "
        "overlap_x_(%)=10\n "
        "overlap_y_(%)=10\n "
        "overlap_z_(%)=10\n "
        "keep_metadata_rotation\n "
        "how_to_store_input_images=[Re-save as multiresolution OME-ZARR]\n "
        "load_raw_data_virtually\n "
        "metadata_save_path=[D:/James/2026-01-23/N001/10 mW/subsampled]\n "
        "image_data_save_path=[D:/James/2026-01-23/N001/10 mW/subsampled]\n "
        "check_stack_sizes\n "
        "compression=Zstandard\n "
        "downsampling_factors=[{ {1,1,1}, {2,2,2}, {4,4,4}, {8,8,8} }]\n "
        "block_size=[{ {128,128,64}, {128,128,64}, {128,128,64}, {128,128,64} }]\n "
        "compute_block_size_factor_x=16\n "
        "compute_block_size_factor_y=16\n "
        "compute_block_size_factor_z=1\n "
        "number_of_threads=19"
))
# run("Detect Interest Points for Registration", "select=file:/D:/James/2026-01-23/N001/10%20mW/subsampled/dataset.xml process_angle=[All angles] process_channel=[All channels] process_illumination=[All illuminations] process_tile=[All tiles] process_timepoint=[All Timepoints] type_of_interest_point_detection=Difference-of-Gaussian label_interest_points=beads subpixel_localization=[Gaussian mask localization fit] interest_point_specification=[Comparable to Sample & small (beads)] downsample_xy=[Match Z Resolution (less downsampling)] downsample_z=1x compute_on=[CPU (Java)]");
IJ.run("Calculate pairwise shifts ...", (
        "select=file:/D:/James/2026-01-23/N001/10%20mW/subsampled/dataset.xml\n "
        "process_angle=[All angles]\n "
        "process_channel=[All channels]\n "
        "process_illumination=[All illuminations]\n "
        "process_tile=[All tiles]\n "
        "process_timepoint=[All Timepoints]\n "
        "method=[Phase Correlation]\n "
        "downsample_in_x=1\n "
        "downsample_in_y=1\n "
        "downsample_in_z=1"
))
IJ.run("Optimize globally and apply shifts ...", (
        "select=file:/D:/James/2026-01-23/N001/10%20mW/subsampled/dataset.xml\n "
        "process_angle=[All angles]\n "
        "process_channel=[All channels]\n "
        "process_illumination=[All illuminations]\n "
        "process_tile=[All tiles]\n "
        "process_timepoint=[All Timepoints]\n "
        "relative=2.500\n "
        "absolute=3.500\n "
        "global_optimization_strategy=[Two-Round using Metadata to align unconnected Tiles and iterative dropping of bad links]\n "
        "fix_group_0-0\n "
        "fix_group_0-1\n "
        "fix_group_0-2\n "
        "fix_group_0-3"
))
IJ.run("Image Fusion", (
        "select=file:/D:/James/2026-01-23/N001/10%20mW/subsampled/dataset.xml\n "
        "process_angle=[All angles]\n "
        "process_channel=[All channels]\n "
        "process_illumination=[All illuminations]\n "
        "process_tile=[All tiles]\n "
        "process_timepoint=[All Timepoints]\n "
        "bounding_box=[All Views]\n "
        "downsampling=1\n "
        "interpolation=[Linear Interpolation]\n "
        "fusion_type=[Avg, Blending]\n "
        "pixel_type=[16-bit unsigned integer]\n "
        "interest_points_for_non_rigid=[-= Disable Non-Rigid =-]\n "
        "produce=[Each timepoint & channel]\n "
        "fused_image=[OME-ZARR/N5/HDF5 export using N5-API]\n "
        "define_input=[Auto-load from input data (values shown below)]\n "
        "export=HDF5\n "
        "compression=[Raw (no compression)]\n "
        "hdf5_file=file:/D:/James/2026-01-23/N001/10%20mW/subsampled/fused2/fused.h5"
))
